export enum ErrorCode {
  // Auth
  AUTH_EMAIL_EXISTS = "AUTH_001",
  AUTH_INVALID_CREDENTIALS = "AUTH_002",
  AUTH_TOKEN_EXPIRED = "AUTH_003",
  AUTH_TOKEN_INVALID = "AUTH_004",
  AUTH_ACCOUNT_DEACTIVATED = "AUTH_005",
  AUTH_INSUFFICIENT_PERMISSION = "AUTH_006",
  AUTH_OTP_EXPIRED = "AUTH_007",
  AUTH_OTP_INVALID = "AUTH_008",
  AUTH_PHONE_REQUIRED = "AUTH_009",
  AUTH_CUSTOMER_DEACTIVATED = "AUTH_010",

  // Validation
  VALIDATION_FAILED = "VAL_001",

  // Resource
  RESOURCE_NOT_FOUND = "RES_001",
  RESOURCE_ALREADY_EXISTS = "RES_002",

  // Payment
  PAYMENT_WEBHOOK_INVALID_SIGNATURE = "PAY_001",
  PAYMENT_RAZORPAY_ORDER_FAILED = "PAY_002",

  // Coupon
  COUPON_NOT_FOUND = "CPN_001",
  COUPON_INACTIVE = "CPN_002",
  COUPON_EXPIRED = "CPN_003",
  COUPON_NOT_YET_VALID = "CPN_004",
  COUPON_FIRST_ORDER_ONLY = "CPN_005",
  COUPON_CUSTOMER_RESTRICTED = "CPN_006",
  COUPON_PAYMENT_METHOD_MISMATCH = "CPN_007",
  COUPON_MIN_ORDER_NOT_MET = "CPN_008",
  COUPON_MAX_USES_REACHED = "CPN_009",
  COUPON_MAX_USES_PER_CUSTOMER_REACHED = "CPN_010",

  // Server
  INTERNAL_ERROR = "SRV_001",
  SERVICE_UNAVAILABLE = "SRV_002",
}
